# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy-editor"
  deploy-editor:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Deploy api
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        pip3 install awscli --upgrade
        pip3 install aws-sam-cli --upgrade
        cd api
        sam build
        sam package --output-template-file packaged.yaml --s3-bucket jdp-delete-me
        sam deploy --template-file packaged.yaml --stack-name jdp-delete-me --s3-bucket jdp-delete-me --capabilities CAPABILITY_IAM --region eu-west-2
    - name: Deploy player
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        cd player
        npm install
        npm run build
        aws s3 sync ./dist/ s3://jdp-delete-me/local-lockdown
    - name: Deploy editor
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        cd editor
        npm install
        npm run build
        aws s3 sync ./dist/ s3://jdp-delete-me/local-lockdown-editor
